export LANG=en_US.UTF-8
export AM_COLOR_TESTS=always
export BUILD=arm64-apple-darwin20.0.0
export BUILD_DIR=/Users/uwe/Development/conda-forge/staged-recipes/recipes/bun/output/bld/rattler-build_bun_1769679891
export PKG_HASH=he8ea13f
export PKG_VERSION=1.3.7
export SUBDIR=osx-arm64
export PIP_NO_INDEX=True
export PIP_CACHE_DIR=/Users/uwe/Development/conda-forge/staged-recipes/recipes/bun/output/bld/rattler-build_bun_1769679891/pip_cache
export FORCE_COLOR=1
export SOURCE_DATE_EPOCH=1769679891
export OSX_ARCH=arm64
export build_platform=osx-arm64
export CPU_COUNT=12
export PIP_NO_BUILD_ISOLATION=False
export MACOSX_DEPLOYMENT_TARGET=11.0
export ARCH=arm64
export CLICOLOR_FORCE=1
export PATH=/Users/uwe/.pixi/envs/rattler-build/bin:/Users/uwe/.pixi/bin:/Users/uwe/.codeium/windsurf/bin:/opt/google-cloud-sdk/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/pmk/env/global/bin:/Library/Apple/usr/bin:/Applications/Keybase.app/Contents/SharedSupport/bin:/Applications/Ghostty.app/Contents/MacOS:/Users/uwe/.local/bin:/Users/uwe/.orbstack/bin
export PKG_NAME=bun
export CONDA_BUILD_STATE=BUILD
export CMAKE_COLOR_DIAGNOSTICS=ON
export RECIPE_DIR=/Users/uwe/Development/conda-forge/staged-recipes/recipes/bun
export CONDA_BUILD=1
export PIP_NO_DEPENDENCIES=True
export MAKE_TERMOUT=1
export CONDA_DEFAULT_ENV=/Users/uwe/Development/conda-forge/staged-recipes/recipes/bun/output/bld/rattler-build_bun_1769679891/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
export HOME=/Users/uwe
export BUILD_PREFIX=/Users/uwe/Development/conda-forge/staged-recipes/recipes/bun/output/bld/rattler-build_bun_1769679891/build_env
export PREFIX=/Users/uwe/Development/conda-forge/staged-recipes/recipes/bun/output/bld/rattler-build_bun_1769679891/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
export PYTHON=/Users/uwe/Development/conda-forge/staged-recipes/recipes/bun/output/bld/rattler-build_bun_1769679891/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
export PIP_IGNORE_INSTALLED=True
export CMAKE_GENERATOR='Unix Makefiles'
export PYTHONNOUSERSITE=1
export PKG_CONFIG_PATH=/Users/uwe/Development/conda-forge/staged-recipes/recipes/bun/output/bld/rattler-build_bun_1769679891/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pkgconfig
export PKG_BUILD_STRING=he8ea13f_0
export CONDA_BUILD_CROSS_COMPILATION=0
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
export SRC_DIR=/Users/uwe/Development/conda-forge/staged-recipes/recipes/bun/output/bld/rattler-build_bun_1769679891/work
export PKG_BUILDNUM=0
export target_platform=osx-arm64
export SHLIB_EXT=.dylib
export host_platform=osx-arm64

export PATH="/Users/uwe/Development/conda-forge/staged-recipes/recipes/bun/output/bld/rattler-build_bun_1769679891/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin:${PATH}"
export CONDA_SHLVL=2
export CONDA_ENV_SHLVL_2_CONDA_PREFIX=/Users/uwe/.pixi/envs/rattler-build
export CONDA_PREFIX=/Users/uwe/Development/conda-forge/staged-recipes/recipes/bun/output/bld/rattler-build_bun_1769679891/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac

export PATH="/Users/uwe/Development/conda-forge/staged-recipes/recipes/bun/output/bld/rattler-build_bun_1769679891/build_env/bin:${PATH}"
export CONDA_SHLVL=2
export CONDA_ENV_SHLVL_2_CONDA_PREFIX=/Users/uwe/.pixi/envs/rattler-build
export CONDA_PREFIX=/Users/uwe/Development/conda-forge/staged-recipes/recipes/bun/output/bld/rattler-build_bun_1769679891/build_env
. /Users/uwe/Development/conda-forge/staged-recipes/recipes/bun/output/bld/rattler-build_bun_1769679891/build_env/etc/conda/activate.d/activate_aaaa_sdkroot_env_osx-arm64.sh
. /Users/uwe/Development/conda-forge/staged-recipes/recipes/bun/output/bld/rattler-build_bun_1769679891/build_env/etc/conda/activate.d/activate_cctools_osx-arm64.sh
. /Users/uwe/Development/conda-forge/staged-recipes/recipes/bun/output/bld/rattler-build_bun_1769679891/build_env/etc/conda/activate.d/activate_clang_osx-arm64.sh
. /Users/uwe/Development/conda-forge/staged-recipes/recipes/bun/output/bld/rattler-build_bun_1769679891/build_env/etc/conda/activate.d/activate_macosx_deployment_target_osx-arm64.sh
. /Users/uwe/Development/conda-forge/staged-recipes/recipes/bun/output/bld/rattler-build_bun_1769679891/build_env/etc/conda/activate.d/activate_rust_osx-arm64.sh
. /Users/uwe/Development/conda-forge/staged-recipes/recipes/bun/output/bld/rattler-build_bun_1769679891/build_env/etc/conda/activate.d/libglib_activate.sh
. /Users/uwe/Development/conda-forge/staged-recipes/recipes/bun/output/bld/rattler-build_bun_1769679891/build_env/etc/conda/activate.d/libxml2-split_activate.sh
